Shopify/homebrew-shopify

- shopify-graphicsmagick.rb
> Add shopify-graphicsmagick recipe

- heka.rb
Will be used to dev-ify Shopify/heka-modules
r: @Shopify/sigint
> Add formula for heka

- nginx-shopify.rb
> nginx: compile with debug

- cs-openssl.rb
> Build with v2 && 3 too

- presto-jdbc.rb
> Use our customized jdbc driver for now

- rds-ssl.rb
@JackMc @JasonMWhite updated the sha for the rds cert. Verified the new cert on my machine and everything is working by doing a few queries to Aurora from datagrip.
> Update the sha for the RDS cert we download from amazon

- presto-cli.rb
@Shopify/data-infrastructure Adding a formula to download the presto cli and add a small wrapper script with the base options to pass.
> Add formula to install presto cli

- mysql-client.rb
Reverts Shopify/homebrew-shopify#19
> Revert "Fix broken client download URL"

- docker-ssh-agent-forward.rb
> Add recipe for the docker ssh agent forwarder

- shopify-graphicsmagick.rb
build GraphicsMagick `--with-webp=yes`
See also https://github.com/Shopify/imagery3/pull/412
cc @nwtn @djoume
> Hackdays - build GraphicsMagick with webp support

- rds-ssl.rb
> updates SHA for rds-ssl package

- rds-ssl.rb
```
shasum -a 256 rds-combined-ca-bundle.pem
```
@JasonMWhite
> Update RDS sha

- nginx-shopify.rb
Ports https://github.com/Shopify/nginx-shopify-build/pull/42 to dev Nginx.
r: @pushrax @csfrancis
> Add vary header length patch

- themekit.rb
This just updates themekit to the newest version. I will wait a few days to merge this to make sure that the newest version is stable.
> Updating Themekit Version

- slate.rb
cc @chrmoritz (thanks for the temporary fix!)
> Fix Slate formula installation

- slate.rb
Forgot to update the sha256 value for the last Slate update.
> Update sha for Slate

- themekit.rb
Reverts Shopify/homebrew-shopify#61
> Revert "Updating themekit version"

- themekit.rb
Just updating to the most stable version of themekit.
> Update the themekit formula

- slate.rb
Updating to the most stable version of Slate.
> Update Slate formula

- oauth-tunnel-client.rb
So @BlakeMesdag helped me get logging working. Also setting `GIN_MODE` to `release`
> Logging fixes

- shopify-graphicsmagick.rb
Sierra is gone, use high sierra
> Add bottle for high sierra

- oauth-tunnel-client.rb
Update the oauth-tunnel-client release to 0.3.0
> Bump oauth-tunnel-client version to 0.3.0

- casks/tunnel-client-app.rb
This includes the starting OAuth Tunnel Client on App start and doing the authentication flow via a WebView.
> Update tunnel-client-app.rb to version 0.2.0

- casks/tunnel-client-app.rb
Fixes issues with opening up broken links
> Update tunnel-client-app.rb to v0.2.1

- casks/tunnel-client-app.rb
- oauth-tunnel-client.rb
updates the shas and links so that they're in the `binaries.shopifykloud.com` bucket
> Change tc path

- themekit.rb
Updating themekit for the latest release
> Updating themekit to v0.8.1

- voucher_client.rb
This pull request adds Voucher Client, which works with our [open source Voucher project](https://github.com/shopify/voucher). This change is to enable developers to install Voucher Client through Homebrew instead of having to setup a Go development environment.
> Add Voucher Client

- themekit.rb
updating to new release of themekit
> Update themekit version 1.0.0

- buildkite-agent.rb
This is directly copied from https://github.com/buildkite/homebrew-buildkite/blob/master/buildkite-agent.rb
The only reason for this is version pinning as we rely on this package for automation purposes.
> Add formula for buildkite-agent

- buildkite-agent.rb
Update to latest version from https://github.com/buildkite/homebrew-buildkite. This is done for version pinning.
> update buildkite-agent to v3.14.0

- ejson2env.rb
This PR just bumps ejson2env to version 2.0.0!
> bumps ejson2env to v2.0.0

- openssl@1.0.rb
While we build up bottles for openssl and wait for https://github.com/Shopify/dev/pull/3862 to merge.
> Adds a copy of openssl as openssl@1.0

- themekit.rb
This is just updating where to grab the new version from.
> Updateing themekit to v1.0.2

- presto-jdbc.rb
update the driver to match the current presto version
https://github.com/Shopify/data-infrastructure/issues/1698
> update presto jdbc to 338

- themekit.rb
```
themekit master % theme version
ThemeKit 1.1.1 darwin/amd64
themekit master % make sha
4b70165660e817e8d6a8f5f1ac8aca5f38ae9f77231f8ea53cc4f42700514a0a  ./build/dist/darwin-amd64/theme
```
> Update Theme Kit to v1.1.1

- shopify-cli.rb
Packaging for release of v1.3.0 of shopify-cli
> Packaging for release of v1.3.0 of shopify-cli

- shopify-cli.rb
Packaging for release of v1.3.1 of shopify-cli
> Packaging for release of v1.3.1 of shopify-cli

- shopify-cli.rb
> Updating shopify-cli to v1.4.0

- presto-jdbc.rb
We are now back on 338. So revert the revert ;)
Reverts Shopify/homebrew-shopify#176
> Revert "downgrade presto 338 to 336"

- voucher_client.rb
This PR bumps Voucher Client to v2.5.2.
> bumps Voucher client to v2.5.2

- themekit.rb
The previous sha was wrong, so I downloaded the binary and recalculated the sha
> Correct the sha on themekit formula

- shopify-graphicsmagick.rb
- shopify-imagemagick@6.rb
See https://github.com/Homebrew/homebrew-core/issues/64166
> Stop depending on :x11

- autoconf@2.69.rb
> Add autoconf@2.69.rb into the root directory

- shopify-cli.rb
Release 1.9.1 addresses issues with extension development. Please see https://github.com/Shopify/shopify-app-cli/pull/1201 and related issues for more details.
> shopify-cli 1.9.1

- themekit.rb
Update themekit version and SHA
> Update themekit to v1.2.0

- shopify-cli.rb
Update `shopify-cli` forumula to 1.12.0 release.
> Release 1.12.0 of shopify-cli

- shopify-cli.rb
Updates shopify-cli formula as part of Release v1.13.0
> Release 1.13.0 of shopify-cli

- shopify-cli.rb
Update Shopify CLI formula to version 1.13.1
> update shopify cli to 1.13.1

- shopify-cli.rb
Update Shopify CLI formula to version 2.0.0 (major change in formula structure)
> Packaging for release of v2.0.0 of shopify-cli

- trino-cli.rb
- trino-jdbc.rb
Add trino cli and trino jdbc casks
https://github.com/Shopify/data-foundations/issues/44
> Add trino cli and trino jdbc casks

- shopify-cli.rb
> Packaging for release of v2.0.2 of shopify-cli

- shopify-cli.rb
> Updated formula for Shopify CLI v2.1.0

- shopify-cli.rb
Bump version of shopify-cli to 2.2.0
> release shopify-cli 2.2.0

- shopify-cli.rb
Related https://github.com/Shopify/shopify-cli/pull/1563
> Release shopify-cli 2.5.0

- shopify-vips.rb
**Tophat instructions:**
```
brew install file:///Users/dbl/src/github.com/Shopify/homebrew-shopify/shopify-vips.rb
```
(path needs to be modified)
> Update shopify-vips to v8.14.0-master rev. 2

- themekit.rb
Related to https://github.com/Shopify/themekit/pull/985
> Bump themekit version

- shopify-vips.rb
Update to latest pre-release of v8.14.0.
> update to libvips v8.14.0 pre-release

- shopify-vips.rb
Update to latest libvips release v8.14.1.
> update libvips to v8.14.1

- shopify-vips.rb
Remove unneeded features we don't need. Improves the build time.
> shopify-vips: remove unneeded features

- certloader.rb
> Add formula for non daemon certloader install

- merlin-certloader.rb
See https://github.com/Shopify/merlin-projects/issues/4581 
A similar issue in trino-certloader https://github.com/Shopify/homebrew-shopify/pull/559
> Fix merlin-certloader 
