lua-nginx-internals-nginx-module.rb, lua-nginx-module.rb, lua-upstream-nginx-module.rb, luajit-shopify.rb, nginx-shopify.rb, ngx-devel-kit.rb
@burke 
Adds formula(s) requires to build an nginx build that is essentially the same as what's built by https://github.com/Shopify/nginx-shopify-build.
I made the nginx modules separate formulas, following the same pattern used by https://github.com/Homebrew/homebrew-nginx/tree/master/Formula. They probably could have been `resource`s within the `nginx-shopify` formula, but `lua-upstream-nginx-module` requires a patch, and I didn't want to have to deal with patching files in a resource.
=> Add nginx-shopify formula

nginx-shopify.rb
@Sirupsen, @es 
Fixes the error on `brew postinstall nginx-shopify`. This removes the `/usr/local/var/www` symlink if it's broken.
=> Fix nginx-shopify post-install

cs-openssl.rb
Build process:
```
==> Downloading https://www.openssl.org/source/openssl-1.0.1f.tar.gz
Already downloaded: /Users/lourens/Library/Caches/Homebrew/cs-openssl-1.0.1f.tar.gz
==> Downloading https://github.com/openssl/openssl/commit/24762dee178bace.diff
Already downloaded: /Users/lourens/Library/Caches/Homebrew/cs-openssl--patch-7cfdb6248054602688c26a8f448c4489881684fe44dfef6727fb5dc0845dfd8b.diff
==> Patching
==> Applying 24762dee178bace.diff
patching file test/smime-certs/smdsa1.pem
patching file test/smime-certs/smdsa2.pem
patching file test/smime-certs/smdsa3.pem
patching file test/smime-certs/smroot.pem
patching file test/smime-certs/smrsa1.pem
patching file test/smime-certs/smrsa2.pem
patching file test/smime-certs/smrsa3.pem
==> perl ./Configure …
```
=> Custom CS 1.0.1f build

presto-cli.rb
This pull request allows users to specify additional parameters such as schema to their Presto cli command without them being silently ignored.
@jduff @Shopify/data-infrastructure
=> Append the rest of the parameters provided to the presto cli command

presto-cli.rb
@JackMc @jduff /cc @Shopify/data-infrastructure 
In order to use `--execute "select * from foo"` (i.e. something with a `*`), you must wrap the `$@` in quotes so that the extra args are interpreted literally. Otherwise, the `*` is interpreted as a glob and you get an error like:
```
⌘ ~/code/shopify/shopify (master) presto --execute "select * from foo"
Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException:
Found unexpected parameters: [CONTRIBUTING.md, Capfile, ...
```
=> Use $@ in quotes for literal args

presto-cli.rb
@stephenminded @jamesemoody for a quick look. Version bump means installs will get the fix for arguments passing as well https://github.com/Shopify/homebrew-shopify/blob/master/presto-cli.rb#L19
=> Bump presto cli to latest

mysql-client.rb
This PR fixes `mysql-client` on macOS Sierra. `5.7.10` has been yanked, but you won't notice this on El Capitan because it will use bottle one.
=> Fix broken client download URL

rds-ssl.rb
This happened *again*, this is a quick fix but we should figure out what changes this cert (is it Amazon rotating it? Do we do something to trigger it?)
Previous incidence of this was #14
=> Change SHA sum for rds-ssl to the new cert that's on S3

rds-ssl.rb
to account for
```
Sams-MacBook-Pro-2% brew install rds-ssl
==> Installing rds-ssl from shopify/shopify
==> Downloading http://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
Error: SHA256 mismatch
Expected: 90567481d386dac26f4c734d83bbe8576955b2a6c84b00fc5113cdf1b7d87ea0
Actual: d8ef0551c3d97d91cc58dc73cd24f2f1d09d992276009d747252fc1dc2c5edef
Archive: /Users/samtalasila/Library/Caches/Homebrew/rds-ssl-0.2.0.pem
To retry an incomplete download, remove the file above.
```
@JackMc
=> updated the expected sha

libzookeeper.rb, luajit-shopify.rb, mysql-client.rb, shopify-libgraphqlparser.rb, shopify-ruby.rb
@Shopify/dev-infra FYI. The process to build these is:
```bash
brew install --build-bottle libzookeeper
brew bottle libzookeeper
s3cmd put libzookeeper*tar.gz s3://whatever/<same filename>
```
I'm using my own s3 bucket here because it's write-once and checksum-verified so it doesn't really matter. You can use whatever bucket and just change the root_url if you ever need to push one.
@boourns because that old libgraphqlparser version is still in here. I added a sierra bottle to it ¯\\\_(ツ)\_/¯
=> Add bottles for Sierra, removing ElCap bottles in most cases.

nginx-shopify.rb
This will install lua-resty-core as part of nginx-shopify.
@charlescng @csfrancis @pushrax
=> this is to make sure lua-restore-core gets installed with nginx-shopify

shopify-terraform.rb
This PR uploads shopify-terraform v0.7.7 to Homebrew. 
r/ @thegedge @sbfaulkner @RyanBrushett
=> Upload shopify-terraform version 0.7.7 to Homebrew

ejson.rb, libzookeeper.rb, mysql-client.rb, shopify-graphicsmagick.rb, shopify-ruby.rb
Switches to using path based bucket access instead of domain so we can piggyback
on Amazon's TLS certificate, and eliminate a MitM attack vector.
=> Use HTTPS root URLs when pouring bottles

themekit.rb
Hey all, I thought this would be the best spot to put a home brew formula for [theme kit](https://github.com/Shopify/themekit). This repo looks like it is used by the public as well as shopifolk so it seemed to fit in. Let me know if I should put it somewhere else.
@Shopify/dev-acceleration
=> Adding a theme kit formula

docker-ssh-agent-forward.rb
@burke PTAL. This recipe was failing while trying to `dev up` Locutus. The reason is that the `Makefile` for 
`docker-ssh-agent-forward` is unconventional. `make all` doesn't do anything Make-ish and also depends on `make install` having run.
🎩 :
```
Eriks-MacBook-Pro:src erikwright$ rm -rf /usr/local/bin/pinata-*
Eriks-MacBook-Pro:src erikwright$ brew uninstall docker-ssh-agent-forward
Uninstalling /usr/local/Cellar/docker-ssh-agent-forward/HEAD-86ec6df... (10 files, 5.4K)
Eriks-MacBook-Pro:src erikwright$ brew install --HEAD https://raw.githubusercontent.com/Shopify/homebrew-shopify/4252c7ea4e1776f507f14a2aab59a02b23220609/docker-ssh-agent-forward.rb
==> Cloning …
```
=> This Makefile is unconventional and only `make install` should be used.

toxiproxy.rb
Updates to newest release here: https://github.com/Shopify/toxiproxy/releases/tag/v2.1.0
@sirupsen
=> Update toxiproxy to 2.1.0

toxiproxy.rb
Fixes problem described here: https://github.com/Shopify/homebrew-shopify/pull/37#issuecomment-265567469
cc @sirupsen
=> Fix `brew upgrade` for toxiproxy cli

echo-nginx-module.rb, nginx-shopify.rb
This adds the https://github.com/openresty/echo-nginx-module to nginx. The echo nginx module is needed to run the tests for https://github.com/Shopify/lua-resty-upstream-healthcheck where we need to implement ssl for healthchecks so that can move to the ☁️ 
@ElvinEfendi @csfrancis 
I 🎩  this on my machine by symlinking `homebrew-shopify -> /Users/leex/projects/shopify/homebrew-shopify` in `/usr/local/Homebrew/Library/Taps/shopify` so that it picks up the changes from here and then I `brew (un)install`ed nginx and it had the echo module.
=> This adds the echo module to nginx

themekit.rb
Themekit had to change an API endpoint usage that will become deprecated soon so it is necessary to have homebrew up to date with the current version.
API issue reference: https://github.com/Shopify/shopify/issues/98379
=> Updating to critical themekit version

nginx-shopify.rb
The production LBs are moving to 1.11.9. This bumps the version to match.
https://github.com/Shopify/nginx-shopify-build/pull/51
@Shopify/traffic @Shopify/webscalenext
=> Upgrade nginx to 1.11.9

cmake30.rb
Not available in upstream `homebrew-versions` anymore.
```
Lourenss-MacBook-Air:homebrew-shopify lourens$ brew install cmake30.rb
Warning: cmake30: No available formula with the name "cmake28" 
'conflicts_with "cmake28"' should be removed from cmake30.rb.
Please report this to the  tap!
Warning: cmake30: No available formula with the name "cmake31" 
'conflicts_with "cmake31"' should be removed from cmake30.rb.
Please report this to the  tap!
==> Downloading http://www.cmake.org/files/v3.0/cmake-3.0.2.tar.gz
Already downloaded: /Users/lourens/Library/Caches/Homebrew/cmake30-3.0.2.tar.gz
==> Downloading https://pypi.python.org/packages/source/S/Sphinx/Sphinx-1.2.3.tar.gz
Already downloaded: /Users/lourens/Library/Caches/Homebrew/cmake30--sphinx-1.2.3.tar.gz
==> python -c import …
```
=> cmake 3.0 for heka

yarn.rb
We've been using quite outdated version of Yarn.
Since November (when we fixed Yarn to 0.16.1) Yarn has been under active development and there are some new features that we could use.
This morning we had issues with connectivity to `https://registry.yarnpkg.com` from Locutus (EC2), that caused all Shopify/shopify builds to [fail](https://locutus.shopify.io/Shopify:shopify:production/log/8a1f893739cd6cd7c1d63bf10ddba0cb638fd732.1.log) until we [made](https://github.com/Shopify/shopify/commit/72fb74cfe54f3e5ea89227f8dc8df031af571830) it to use `registry.npmjs.org`. This is not particularly related to the package manager, but using `yarn install --verbose` could make it easier to discover that the problem was caused by the network issues to the particular host. The `--verbose` flag is not …
=> Update Yarn to 0.21.3

toxiproxy.rb
This bumps toxiproxy to version 2.1.1. ([See release here.](https://github.com/Shopify/toxiproxy/releases/tag/v2.1.1))
@sirupsen
=> bump toxiproxy to 2.1.1

slate.rb
Adds Shopify's NPM [Slate](https://github.com/Shopify/slate-cli) package.
For review @burke @airhorns @stefanmb @bouk @casperisfine @NathanPJF
=> Add slate.rb

toxiproxy.rb
Fixes the SHA for the current release of toxiproxy. Addresses https://github.com/Shopify/homebrew-shopify/issues/55.
=> Fix toxiproxy SHA

slate.rb
This PR is a fix in response to https://github.com/Shopify/homebrew-shopify/pull/52#issuecomment-311483637 - which removes the `inreplace` command as a temporary fix. Also updates Slate to the latest version.
cc @NathanPJF
=> Update Slate to 0.11.0

shopify-terraform.rb
this PR bumps shopify-terraform to 0.7.13 (like in #31)
=> update terraform to 0.7.13

yarn.rb
Asset integrity problems are affecting many devs.  Upgrading to 0.27.5 has fixed it for at least one dev.
=> Upgrade to yarn@0.27.5

lua-nginx-module.rb, nginx-shopify.rb
@Shopify/edgescale, @Shopify/routing 
Related: https://github.com/Shopify/nginx-routing-modules/pull/1506
In https://github.com/Shopify/cookbooks/pull/15135 we are bumping NGINX to `1.13.4-1` as per https://github.com/Shopify/nginx-shopify-build/pull/56. This pull request updates the version to match.
=> Update NGINX to version 1.13.4

echo-nginx-module.rb
@Shopify/edgescale, @Shopify/routing 
This should have shipped with #64. I'm just going to merge since `brew install nginx-shopify` is currently broken with the following error:
```
marc:nginx-routing-modules marcbarry$ brew install nginx-shopify
==> Installing nginx-shopify from shopify/shopify
==> Downloading https://nginx.org/download/nginx-1.13.4.tar.gz
Already downloaded: /Users/marcbarry/Library/Caches/Homebrew/nginx-shopify-1.13.4.tar.gz
==> ./configure --prefix=/usr/local/Cellar/nginx-shopify/1.13.4 --with-http_ssl_module --with-http_realip_module --with-http_stub_status_module --with-http_geoip_module --with-htt
==> make install
Last 15 lines from /Users/marcbarry/Library/Logs/Homebrew/nginx-shopify/02.make:
-o objs/addon/src/ngx_http_echo_foreach.o \ …
```
=> Bump echo-nginx-module to version 0.61.

lua-upstream-nginx-module.rb
@Shopify/edgescale, @Shopify/routing 
See https://github.com/Shopify/nginx-shopify-build/pull/59 for details.
=> Updates lua-upstream-nginx-module to version 0.07

nginx-shopify.rb
@Shopify/edgescale 
These patches are applied to https://github.com/Shopify/nginx-shopify-build/ and are required in order for tests to pass during local development.
In https://github.com/Shopify/homebrew-shopify/commit/6bd528ce170ce6e706d1c8db7eb52b51ab7b5b68 I removed these patches since they weren't applying properly. I created new Gists for the patches and added the secret link so that people can edit them in the future. I checked and unfortunately there is no way to have a Gist as part of an organization.
=> Reapply patches to nginx-shopify

nginx-shopify.rb
@Shopify/edgescale, @csfrancis 
Related: https://github.com/Shopify/cookbooks/pull/15293, https://github.com/Shopify/nginx-shopify-build/pull/68
This bumps us to an NGINX version matching what is deployed.
=> Bump NGINX version to 1.13.5

ejson.rb
We will need to upload the new version on your s3, or maybe switch to some Shopify S3 bucket?
Also not sure if we need a Sierra bottle as well.
=> Update ejson to 1.1.0

oauth-tunnel-client.rb
This package has the oauth-client-id and oauth-secret built into the binary in order to set up a connection to Presto (`ods1`) without any additional configuration.
=> Bumping Oauth-Client Binary

luajit-shopify.rb
I'm not sure why, but the sha of the specific diff seems to have changed. I ran into that issue when setuping my new computer.
```
maximebedard(~/Github/nginx-routing-modules) (refactor-allocator-to-accept-cloud-dcs) > brew install nginx-shopify
==> Installing nginx-shopify from shopify/shopify
==> Installing dependencies for shopify/shopify/nginx-shopify: luajit-shopify, ngx-devel-kit, lua-nginx-module, lua-upstream-nginx-module, lua-nginx-internals-nginx-module, echo-nginx-module
==> Installing shopify/shopify/nginx-shopify dependency: luajit-shopify
==> Downloading http://luajit.org/download/LuaJIT-2.1.0-beta2.tar.gz
Already downloaded: /Users/maximebedard/Library/Caches/Homebrew/luajit-shopify-2.1.0-beta2.tar.gz
==> Downloading …
```
=> [LuaJIT] Update sha of LuaJIT/issues/180 patch

redshift-ssl.rb
**What:** 
Updates the SHA for the `redshift-ssl` cask. 
**Why:**
Found while onboarding and trying to install the Redshift CA cert: 
```
starscream (master) $ brew install redshift-ssl
==> Installing redshift-ssl from shopify/shopify
==> Downloading https://s3.amazonaws.com/redshift-downloads/redshift-ssl-ca-cert.pem
Error: SHA256 mismatch
Expected: f63b3098250346eee57b63a2b150cb4fd75c3bb70bdd36bc1ac7de6d462499e4
Actual: e77daa6243a940eb2d144d26757135195b4bdefd345c32a064d4ebea02b9f8a1
```
And it seems Amazon agrees!
```
$ curl https://s3.amazonaws.com/redshift-downloads/redshift-ssl-ca-cert.pem | shasum -a 256
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total …
```
=> update redshift-ssl SHA

oauth-tunnel-client.rb
The current log location sets the dir ownership to root when it does not exist previously, which was causing the client startup to fail. 
This moves the logs into a more logical place anyways.
=> Changing log ownership

mint.rb
I'm adding a customized version of a command line tool for running Swift packages to enable easy installation of some of our tooling.
=> Adding Mint (swift package runner) tool

mysql-client.rb
This fixes the following error:
```
Installing shopify/shopify/mysql-client
┃    Cloning into '/usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify'...
┃    ==> Installing mysql-client from shopify/shopify
┃    ==> Installing dependencies for shopify/shopify/mysql-client: cmake
┃        Installing cmake dependency for shopify/shopify/mysql-client
┃    ==> Installing shopify/shopify/mysql-client
┃    Warning: Calling ENV.minimal_optimization is deprecated!
┃    There is no replacement.
┃    /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/mysql-client.rb:41:in `install'
┃    Please report this to the shopify/shopify tap!
```
A similar fix was applied to `homebrew-core`: https://github.com/Homebrew/homebrew-core/commit/71797376c000217bfdf4bd508f264a1c5a526b42
=> Remove ENV.minimal_optimization from mysql formula

libcidr-shopify.rb, nginx-shopify.rb, patch/mac_os_libcidr_support.patch
Create a homebrew formula for the libcidr-shopify utility library (https://github.com/Shopify/libcidr-shopify) @Shopify/edgescale 
link to patch gist: https://gist.github.com/fmejia97/ad72a1f2b5d4b77a2921f32d861850b8
=> Add formula for libcidr-shopify package

oauth-tunnel-client.rb
To be able to use dev to upgrade brew packages for us, we need to use [SemVer version numbers](https://semver.org/) (e.g. "0.2.0", not "0.2").
=> Make oauth-tunnel-client version follow SemVer

casks/tunnel-client-app.rb
After this change, users that have the Shopify brew tap can install the Tunnel Client App (a macOS application that wraps the `oauth-tunnel-client`).
Homebrew Cask is the way to install applications (e.g. google chrome, IDEs, macOS apps, etc).
```shell
brew tap shopify/shopify # get Shopify's brew tap
brew cask install tunnel-client-app # install the Tunnel Client App to /Applications
```
Running `brew cask install tunnel-client-app`:
```shell
$ brew cask install tunnel-client-app
==> Satisfying dependencies
==> Downloading https://storage.googleapis.com/tunnel-client-app-binaries/TunnelClient.app.tar.gz
Already downloaded: /Users/nicholaswu/Library/Caches/Homebrew/Cask/tunnel-client-app--1.0.0.tar.gz
==> Verifying checksum for Cask tunnel-client-app
==> Installing Cask tunnel-client-app …
```
=> Create casks/tunnel-client-app.rb to install Tunnel Client App

cmake30.rb, cs-openssl.rb, luajit-shopify.rb, presto-cli.rb, shopify-graphicsmagick.rb, shopify-libgraphqlparser.rb, shopify-ruby.rb, toxiproxy.rb
Homebrew has deprecated its `.undent` helper now that all Homebrew installations use Ruby 2.3. Ruby 2.3 includes a native version of this form of heredoc, the squiggly heredoc (`<<~EOS`). Homebrew will print deprecation warnings for all of these and, for users running with the Homebrew developer mode on, will refuse to run the method entirely.
This supersedes #91, which only updated one formula, and fixes #89.
cc @fmejia97 and @jules2689, who updated these most recently.
=> Replace undent heredocs with Ruby 2.3 native heredocs

casks/tunnel-client-app.rb
install logs:
```
$ brew cask reinstall tunnel-client-app
==> Satisfying dependencies
==> Downloading https://storage.googleapis.com/tunnel-client-app-binaries/TunnelClient.app-430b1d1967a808ad919f43a3617bb74f595bb528.tar.gz
==> Verifying checksum for Cask tunnel-client-app
==> Uninstalling Cask tunnel-client-app
==> Backing App 'TunnelClient.app' up to '/usr/local/Caskroom/tunnel-client-app/0.1.0/TunnelClient.app'.
==> Removing App '/Applications/TunnelClient.app'.
==> Purging files for version 0.1.0 of Cask tunnel-client-app
==> Installing Cask tunnel-client-app
==> Moving App 'TunnelClient.app' to '/Applications/TunnelClient.app'.
🍺  tunnel-client-app was successfully installed!
```
=> Update tunnel-client-app.rb to latest binary

oauth-tunnel-client.rb
Get the latest changes to `oauth-tunnel-client` including new endpoint `/api/status`.
Will also update the clients of this brew package.
Success logs:
```
$ brew upgrade oauth-tunnel-client
^C==> Upgrading 1 outdated package, with result:
shopify/shopify/oauth-tunnel-client 0.2.1
==> Upgrading shopify/shopify/oauth-tunnel-client
==> Downloading https://storage.googleapis.com/oauth-tunnel-binaries/oauth-tunnel-client-binaries-b1dfd5b0f7d9c5abd0601192e1132fc03b1676f1.tar.gz?GoogleAccessId=pipa-production@sh
chmod 750 /usr/local/var/log/oauth-tunnel-client/
==> Caveats
To have launchd start shopify/shopify/oauth-tunnel-client now and restart at login:
brew services start shopify/shopify/oauth-tunnel-client
==> …
```
=> Update oauth-tunnel-client.rb to 0.2.1

oauth-tunnel-client.rb
Missed the URL in the last commit at #97
=> Update oauth-tunnel-client URL for v0.2.1

presto-cli.rb
This PR updates the homebrew presto_cli formula to support the new presto GCP cluster instead of the DC cluster.
Tested via `brew install https://raw.githubusercontent.com/Shopify/homebrew-shopify/update-presto-gcp/presto-cli.rb`
Alternatively, if one still wants to use the old DC presto server you can specify server url when you invoke the cli, ie: `$ presto --server ods1.hu131.data-chi.shopify.com:8082`
@alanctgardner @andrewryder @cfournie for review
=> Update presto server from DC to GCP

nginx-shopify.rb
Related: https://github.com/Shopify/nginx-shopify-build/pull/82, https://github.com/Shopify/cookbooks/pull/16271, https://github.com/Shopify/shopify-docker-images/pull/671
Matches us with https://github.com/Shopify/nginx-shopify-build/pull/82 and https://github.com/Shopify/nginx-shopify-build/pull/82.
=> Bump to NGINX version 1.13.9

shopify-imagemagick.rb
Problem seems to be here: https://github.com/ImageMagick/ImageMagick6/commit/e819f52a2a641774cd4f2e9cbfde3d5a1daa8cea where 5->6, this is for 6.9.9-41 release, so based this on the https://github.com/Homebrew/homebrew-core/blob/e9f6bb3a73fa27ba5d30e3346fbc641b1e85e61f/Formula/imagemagick%406.rb 6.9.9-40 formula version.
=> Add imagemagick at old version supported by rmagick

shopify-imagemagick@6.rb
Reverts Shopify/homebrew-shopify#108
Should fix #109.  Can address a bottle with png support after.
=> Revert "Add bottle for imagemagick"

secret-sender.rb
:tophat: instructions:
```
dev clone homebrew-shopify
cp secret-sender.rb /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify
brew install shopify/shopify/secret-sender
man secret-sender
```
=> Add secret-sender

oauth-tunnel-client.rb
Update homebrew to the correctly tagged 0.3.2 release.
=> Bump version of oauth-tunnel-client to 0.3.2

oauth-tunnel-client.rb
Used the incorrect SHA in the previous PR, causing issues updating OAuth Tunnel Client in Homebrew. This PR fixes this to include the correct SHA.
=> updated incorrect build SHA

luajit-shopify.rb
After applying this change locally, I was able to build luajit-shopify on High Sierra. I stole this change from the default `luajit` Formula:
https://github.com/Homebrew/homebrew-core/blob/1cfa45642ba20143d8606a069621a534a19d2ac0/Formula/luajit.rb#L29-L33
=> Get luajit-shopify building again on High Sierra

casks/phantomjs.rb
So Homebrew `phantomjs` build is FUBAR'd as with most recent XCode/CLT it does not build on macOS High Sierra and Mojave.
See https://github.com/Homebrew/homebrew-core/issues/32402 and https://github.com/Homebrew/homebrew-cask/pull/52595.
While it seems like there's a chance that `phantomjs` will be added to upstream Cask repo, it seems like some maintainers are not very fond of having abandonware in Homebrew and suggest to move it to our own tap instead:
> Phantomjs is abandoned software. We don’t really like keeping those. You may wish to consider hosting your own tap for it.
cc: @Shopify/datadelivery @Shopify/dev-acceleration
=> Add phantomjs cask to Shopify tap

docker-ssh-agent-forward.rb
Based on a HackerOne report, it appears as though this does not properly authenticate the source repository. 
We have forked the repository and versioned it out.
@Shopify/appsec
=> Add SHA256 check to docker-ssh-agent-forward.rb

qt@5.5.rb
https://github.com/Shopify/kit/ depends on the gem `capybara-webkit` which requires `qt 5.5` to be built. The latter was supplied via Homebrew, but it no longer compiles under macOS Mojave, and it was [dropped from Homebrew](https://github.com/Homebrew/homebrew-core/issues/32467) in Oct 2018.
/cc: @sealabcore @jppommet
=> Archive of qt 5.5, since it won't build in Mojave

qt@5.5.rb
Homebrew looks to a different directory by default for finding bottles for formulas defined in taps. For Shopify's tap, that URL is https://homebrew.bintray.com/bottles-shopify/
Since we aren't creating the bottles ourselves, and actually want the historic Homebrew ones, we need to explicitly specify the default Homebrew root.
More documentation [here](https://docs.brew.sh/Bottles) and a [Discourse question](https://discourse.brew.sh/t/default-root-url-for-custom-taps/1245) on this very topic.
=> We want to use Homebrew's default bottle URL for qt@5.5

mint.rb
Bumps to the Swift 5 compatible mint 0.8.1 release on new repo.
=> Update mint to 0.8.1

shopify-graphicsmagick.rb
Fixing https://github.com/Shopify/homebrew-shopify/issues/109 again as https://github.com/Shopify/homebrew-shopify/pull/110 removed imagemagick's bottle
It seems like the bottled version of graphicsmagick was built without libpng being present, which means you can do things like `curl https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png | /usr/local/bin/gm identify -` which mogrify in core relies on.
`otool -L ./gm` (with the `gm` binary found in https://storage.googleapis.com/shopify-dev-public/shopify-graphicsmagick-1.4.020150705_2.high_sierra.bottle.tar.gz) produces:
```
@@HOMEBREW_CELLAR@@/shopify-graphicsmagick/1.4.020150705_2/lib/libGraphicsMagick.3.dylib (compatibility version 17.0.0, current version 17.0.0) …
```
=> remove graphicsmagick bottle as it has no png support

shadowenv.rb
🎩 : 
- Copy this file to `/usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/`
- `rm /usr/local/bin/shadowenv` - you'll start to see `__shadowenv_hook:5: no such file or directory: /usr/local/bin/shadowenv` in your terminal
- If you've installed the manpages, get rid of them too:
- `rm /usr/local/share/man/man1/shadowenv.1`
- `rm /usr/local/share/man/man5/shadowlisp.5`
- `brew install --build-from-source shopify/shopify/shadowenv` - takes a while, hook error goes away
- `shadowenv -V` => `shadowenv 0.3.1`
- `man shadowenv` should work
- `man shadowlisp` should work
- `brew uninstall shopify/shopify/shadowenv` - hook error comes back
- `brew install shopify/shopify/shadowenv` - goes quickly, Pouring shadowenv-0.3.1.mojave.bottle.tar.gz, hook error goes away
=> Add shadowenv package 

keychain-status.rb
See README on https://github.com/Shopify/keychain-status
🎩 
```
$ brew test ./keychain-status.rb
Testing keychain-status
==> /usr/local/Cellar/keychain-status/0.1.0/bin/keychain-status /Library/Keychains/System.keychain
$ brew install ./keychain-status.rb
==> Downloading https://github.com/Shopify/keychain-status/releases/download/0.1.0//keychain-status-0.1.0.mojave.bottle.tar.gz
Already downloaded: /Users/seb/Library/Caches/Homebrew/downloads/71402871876845d9aa545d959ce186bc30755c2bb05b63c25e52754a9dbd902e--keychain-status-0.1.0.mojave.bottle.tar.gz
==> Pouring keychain-status-0.1.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/keychain-status/0.1.0: 4 files, 18.5KB
$ keychain-status
unlocked: true
readable: true
writable: true
```
=> Add keychain status

pyenv@1.2.11.rb
To resolve https://discourse.shopify.io/t/dev-up-fails-to-install-python-no-module-named-pyexpat/3680/6, until a new release eliminates this problem.
https://discourse.shopify.io/t/dev-up-fails-to-install-python-no-module-named-pyexpat/3680/6
=> Pin pyenv to version that doesn't fail on Mojave

presto-cli.rb, presto-jdbc.rb
This updates the Presto JDBC and Presto CLI versions to the latest (0.222) for brew installs.
I really don't know what this Shopify version is of 0.148 or what it's for (maybe just renamed because it was pulling from our own S3 bucket?); I can use the latest JDBC driver without issue.
=> update presto jdbc/cli to latest presto versions

presto-jdbc.rb
This adds a symlink for the `presto-jdbc` driver so that when users upgrade/install the driver they can just point to latest in the root presto folder (and not expect it to move/change as long as they provide the latest link to DataGrip)
=> symlink presto

secret-sender.rb
I got part way through this guide https://docs.google.com/document/d/1IYDdjrTEiDulZ9yGLlqL7bR50PBO3u2oDKngum2joXo/edit# (original is at http://notes.burke.libbey.me/bumping-private-homebrew/)
Steps 1-5 are all good for me now, but I get stuck on:
6. `brew install --build-bottle ./secret-sender.rb`
7. `brew bottle secret-sender` 💥 
💥 : This command returns
`Error: Formula not installed or up-to-date: shopify/shopify/secret-sender` i.e. https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bottle.rb#L212 for some reason ... 🤔
=> Update secret-sender formula for v2.0.0

buildkite-agent.rb
This updates the Shopify Homebrew `buildkite-agent` to 3.15.2, to incorporate new features.
=> Update buildkite-agent to 3.15.2

openssl.rb
"I felt a great disturbance in the Force, as if millions of voices suddenly cried out in terror and were suddenly silenced. I fear something terrible has happened."
The core openssl formula was removed by https://github.com/Homebrew/homebrew-core/commit/0349a7ca7. Only the openssl@1.1 formula survives.
=> Adds the last revision of the openssl formula from homebrew

lua-nginx-module.rb, luajit-shopify.rb, nginx-shopify.rb
Picks up support for openssl@1.1, openssl@1.0 being EOL.
Fixes https://github.com/Shopify/network-foundations/issues/226
=> Bump lua-nginx-module to 0.10.15

presto-jdbc.rb
Currently if you try to run `brew install presto-jdbc` it fails
with a 501 HTTPS Required error. Since the Maven repo is using
HTTPS, the url should also be updated accordingly.
=> Change presto-jdbc homepage and url to use https

shopify-cli.rb
This adds the first version of the new Shopify CLI to the cask.
=> Add shopify-cli v0.9.1

shopify-cli.rb
Bumping version to 1.0.3 to match the gem.
=> Updating shopify-cli formula

presto-jdbc.rb
Reverts Shopify/homebrew-shopify#175
we are reverting presto versions (mode does not have this driver version yet) so we should revert this too. currently 336 is deployed
=> downgrade presto 338 to 336

shopify-cli.rb
While `tar -xzf` works on macOS even if the given file is not compressed, on Linux it will complain.
Since the `.gem` file is really an uncompressed tarball, `tar -xf` will work on both macOS and Linux as the first command of the install formula.
Note that this PR fixes [#814](https://github.com/Shopify/shopify-app-cli/issues/814) for the current release of Shopify App CLI; PR [#846](https://github.com/Shopify/shopify-app-cli/pull/846) fixes it for future releases.
🎩 Tophatted on macOS Catalina and Ubuntu 20.04
=> Removed 'z' from first tar command

qt@5.5.rb
All versions supported by homebrew work, so no need to specify.
Fixes #186
=> Remove MacOS dependency in qt

shopify-cli.rb
In the interest of automating formula updates with Github Actions, the url can't have a variable or it throws an error.
=> Remove version in url

shopify-cli.rb
This is causing brew update to fail because the version # is being hardcoded, thus throwing error
```
Error: You need to bump this formula manually since the new version
and old version are both 1.4.0.
```
=> Remove version to allow automated brew update

voucher_client.rb
Didn't commit my change that fixed the hash, this fixes it now.
=> bumps Voucher client to v2.5.2

bazel@10.rb
Java appears not to be able to be built on newer versions of MacOS, thus OpenJDK should be preferred. Fixes https://github.com/Shopify/homebrew-shopify/issues/201
=> Change dependency from Java to OpenJDK

buildkite-agent.rb
Homebrew no longer supports `ARGV.value` or options that are not flags (i.e. `--with-foo`).
```
Error: An exception occurred within a child process:
NoMethodError: undefined method `value' for #<Array:0x00007f959b884040>
Did you mean?  values_at
/usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/buildkite-agent.rb:18:in `agent_token'
/usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/buildkite-agent.rb:75:in `install'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:30:in `block in install'
...
```
=> Fix Buildkite Agent Formula

Formula/autoconf@2.69.rb
2.70 and more importantly 2.71 cause lots of issues with ruby, so it is useful to be able to pin to 2.69.
=> Add autoconf 2.69 to the backported packages

bazel@10.rb, cmake30.rb, ejson.rb, ejson2env.rb, libgda.rb, libzookeeper.rb, luajit-shopify.rb, openssl.rb, openssl@1.0.rb, pyenv@1.2.11.rb, qt@5.5.rb, secret-sender.rb, shopify-libgraphqlparser.rb, shopify-ruby.rb, yarn.rb
Fixes deprecation errors as exampled below with
`brew style --fix --only-cops FormulaAudit/BottleFormat *.rb`
Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `>
Please report this issue to the shopify/shopify tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix >
/usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/ejson.rb:8
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update t>
Please report this issue to the shopify/shopify tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix >
/usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/ejson.rb:9
=> Deprecation fixes

shopify-cli.rb
New release of the Shopify App CLI: 1.11.0.
=> Release 1.11.0 of shopify-cli

shopify-imagemagick@6.rb
ImageMagick `6.9.9-40` is no longer hosted by ImageMagick.
Bump version to `6.9.9-51`. I made these changes directly to my brew configuration locally and was able to start Identity.
=> Bump ImageMagick to 6.9.9-50

nginx-shopify.rb
It would appear that newer versions of Homebrew have removed the `userpaths` functionality, as inferred via https://github.com/denji/homebrew-nginx/issues/383 and myself running into an error upon trying to install this recipe as-is
That user path seems to have only been used to inherit the `$PATH` such that a subsequent later call to `brew` would succeed.
So; 
* Remove the call to the deprecated `env :userpaths`
* Update the call to `brew` to use a full path based on the exposed constant of `HOMEBREW_PREFIX` which we depend on elsewhere in this formula.
I've 🎩  this locally, with some assistance from @spike01 and we believe that this will be necessary for any future new starters to be able to get `nginx-shopify` rolling on their newly issued Macs.
=> Update nginx-shopify to not depend on deprecated Homebrew features

shopify-cli.rb
New `shopify-cli` version: `v2.2.0` -> `v2.2.1`
=> Shopify CLI 2.2.1

oauth-tunnel-client.rb
Bump the version and let brew set the `plist_name` based on the DSL Macro.  I think brew used to force it, but it doesn't anymore and it causing the following error on updated systems:
```
$ brew services start oauth-tunnel-client
Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/mbruce/Library/LaunchAgents/homebrew.mxcl.oauth-tunnel-client.plist` exited with 5.
```
because the Label doesn't match:
```
mbruce@Matthews-MacBook-Pro-2 starscream (mb-update-hive-targets-global) $ cat /Users/mbruce/Library/LaunchAgents/homebrew.mxcl.oauth-tunnel-client.plist
<?xml version="1.0" encoding="UTF-8"?>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" …
```
=> use plist_name DSL for oauth_tunnel_client label

shopify-cli.rb
I'm updating the Brew formula of the recently released version of the Shopify CLI, [2.3.0](https://github.com/Shopify/shopify-cli/pull/1486)
=> Release Shopify CLI 2.3.0

toxiproxy.rb
Bump toxiproxy version.
Changes: https://github.com/Shopify/toxiproxy/releases/tag/v2.2.0
=> Bump toxiproxy to v2.2.0

buildkite-agent.rb
Issue: https://github.com/Shopify/mac-infra/issues/457
The current version that we install for the buildkite-agent i.e. `v3.15.2` does not support M1 (ARM) machines. To add support for ARM machines, the buildkite agent is updated to v3.33.3 for **M1 (ARM) machines** only. The default still remains as v3.15.2 for other machines i.e Intel machines. It is better to look at upgrading the buildkite-agent for the Intel machines in a seperate PR as that might introduce some breaking changes to the current fleet of Intel Mac Mini Hosts.
This change is copied from https://github.com/buildkite/homebrew-buildkite/blob/master/buildkite-agent.rb
=> Update buildkite agent to 3.33.3 for ARM machines

shopify-cli.rb
This PR updates the shopify-cli formula to point to the [recently published](https://github.com/Shopify/shopify-cli/pull/1893) version of the Shopify CLI, 2.8.0.
=> Shopify CLI 2.8.0

nginx-shopify.rb
* Update Nginx itself
* Target OpenSSL1.1 explcitly to avoid OpenSSL3 being inadvertently installed
=> nginx-shopify version bumps

voucher_client.rb
* on [2020-11-18](https://cloud.google.com/blog/products/devops-sre/introducing-voucher-service-help-secure-container-supply-chain),  `voucher` migrated to the `grafeas` organization which broke this formula.
* on `2021-09-14`, voucher-v2.6.0 added binaries for the `darwin/arm64` platform
* on `2022-01-04` the latest and greatest voucher-v2.7.0 was released
This PR rolls these changes up such that https://github.com/grafeas/voucher/releases/tag/v2.7.0 is the supported version of voucher.
=> voucher_client-v2.7.0

voucher_client.rb
Add `linux/amd64` and `linux/arm64` binaries to voucher_client v2.7.0.
This fixes an issues where the "Unsupported platform" error would cause tapping to fail outside of MacOS.
Checksums should match https://github.com/grafeas/voucher/releases/download/v2.7.0/checksums.txt
=> voucher_client: linux support

shopify-cli.rb
An [off-schedule release](https://development-lifecycle--atc-updates.docs.shopify.io/releasing) of the Shopify CLI
=> Release Shopify CLI 2.10.0

oauth-tunnel-client.rb, trino-certloader.rb
Conductor/Trino will use `certloader` run as a Homebrew service powered by launchd and Mac's plist files similar to how the `oauth-tunnel-client` is ran to automatically manage mTLS certificates.
This PR will enable:
```bash
dev github auth
brew install trino-certloader
brew services start trino-certloader
➜ brew services info trino-certloader
trino-certloader (homebrew.mxcl.trino-certloader)
Running: ✔
Loaded: ✔
Schedulable: ✘
➜ tree $(brew --prefix)/var/trino-certloader/certs/
/opt/homebrew/var/trino-certloader/certs/
├── ca.crt -> .current/ca.crt
├── cert_and_key.pem -> .current/cert_and_key.pem
├── tls.crt -> .current/tls.crt
└── tls.key -> .current/tls.key
```
`Certloader` uploads its released binaries as Github releases. Homebrew does not support private repos/releases by default so …
=> Add `trino-certloader` cask

shopify-cli.rb
The shopify-cli Homebrew formula [causes installation issues](https://github.com/Shopify/shopify-cli/issues/2057#issuecomment-1060640948) when Ruby hasn't been previously installed through Homebrew. This PR fixes it.
=> Fix the shopify-cli formula

shopify-cli.rb
I'm releasing a new version of the Shopify CLI, [2.15.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.15.0)
=> Update Shopify CLI to 2.15.0

shopify-cli.rb
I'm releasing a new version of the Shopify CLI, [2.15.1](https://github.com/Shopify/shopify-cli/releases/tag/v2.15.1)
=> Update Shopify CLI to 2.15.1

shopify-cli.rb
I'm releasing a new version of the Shopify CLI, [2.15.2](https://github.com/Shopify/shopify-cli/releases/tag/v2.15.2)
=> Update Shopify CLI to 2.15.2

trino-certloader.rb
Increase `trino-certloader` to use a longer TTL and bump to v0.3.0 of certloader
=> Increase `trino-certloader` to use a longer TTL and bump to v0.3.0 of certloader

shopify-cli.rb
I'm releasing a new version of the Shopify CLI, [2.15.3](https://github.com/Shopify/shopify-cli/releases/tag/v2.15.3)
=> Update Shopify CLI to 2.15.3

shopify-cli.rb
I'm releasing a new version of the Shopify CLI, [2.15.4](https://github.com/Shopify/shopify-cli/releases/tag/v2.15.4)
=> Update Shopify CLI to 2.15.4

shopify-cli.rb
I'm releasing a new version of the Shopify CLI, [2.15.6](https://github.com/Shopify/shopify-cli/releases/tag/v2.15.6)
=> Update Shopify CLI to 2.15.6

shopify-cli.rb
I'm releasing a new version of the Shopify CLI, [2.16.1](https://github.com/Shopify/shopify-cli/releases/tag/v2.16.1)
=> Update Shopify CLI to 2.16.1

merlin-certloader.rb
Straight copy of the trino-certloader but configured to create certs for Merlin adhoc workspaces instead.
If there's a way to share code between formulas in this repo that would be useful, but there are no docs.
=> Add formula for merlin certloader

shopify-cli.rb
I'm releasing a new version of the Shopify CLI, [2.17.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.17.0)
=> Update Shopify CLI to 2.17.0

merlin-certloader.rb, trino-certloader.rb
Bumps Trino and Merlin certloader to v0.3.1 which includes changes from this release: https://github.com/Shopify/certloader/releases/tag/0.3.1
The most important changes in 0.3.1 are here: https://github.com/Shopify/certloader/commit/c3a722b76b27b53457990ea894e6f32d7dcad6af
=> Bump trino and merlin certloader to version 0.3.1

shopify-vips.rb
Add conflict with the Homebrew version of `vips` - we shouldn't have both versions installed.
=> shopify-vips: add conflict with vips package

shopify-vips.rb
Homebrew created a new formula for glib utilities (`glib-utils`) which were previously provided by `glib`: https://github.com/Homebrew/homebrew-core/pull/103916
libvips build depends on these utilities.
=> shopify-vips: fix build: add missing build dependency glib-utils

merlin-certloader.rb, trino-certloader.rb
Since we download `certloader` binaries from a Shopify private Github repository rather than a public bucket, we need to use a user's github auth credentials to download the binary. Previously it was assumed that a user only ever had a single auth credential in the `dev github auth` credential store, but some users have multiple if they refresh old expired tokens. This seems especially prevalent for longer tenured folks at Shopify.
We already [handle this in `certloader`](https://github.com/Shopify/certloader/blob/master/pkg/vault/github.go#L75-L78), but did not in the homebrew cask. Users would see errors when trying to install `trino-certloader` or `merlin-certloader` that looked like:
I tested this by adding a dummy auth credential in my dev github auth creds store.
```
➜ cat …
```
=> Handle multiple github auth creds in `dev github auth` credential store

shopify-vips.rb
Add missing build dependency: `gobject-introspection`
Building `shopify-vips` started to fail out of the nowhere - I think we should consider adding tests to this repo at some point.
**Tophat instructions:**
```
brew install file:///Users/dbl/src/github.com/Shopify/homebrew-shopify/shopify-vips.rb
```
(path needs to be modified)
=> shopify-vips: Add missing build dependency: gobject-introspection

shopify-cli.rb
I'm releasing a new version of the Shopify CLI, [2.22.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.22.0)
=> Update Shopify CLI to 2.22.0

shopify-cli.rb
I'm releasing a new version of the Shopify CLI, [2.24.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.24.0)
=> Update Shopify CLI to 2.24.0

shopify-cli.rb
I'm releasing a new version of the Shopify CLI, [2.25.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.25.0)
=> Update Shopify CLI to 2.25.0

shopify-cli.rb, shopify-cli@2.rb
I'm releasing a new version of the Shopify CLI, [2.29.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.29.0)
=> Update Shopify CLI to 2.29.0

casks/zulu-jdk17.rb
Trino 400 requires JDK 17 > 17.04
This PR Upgrades the JDK 17 version to 17.05
=> Upgrade jdk 17 version

shopify-cli@2.rb
I'm releasing a new version of the Shopify CLI, [2.30.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.30.0)
=> Update Shopify CLI to 2.30.0

shopify-cli@2.rb
I'm releasing a new version of the Shopify CLI, [2.32.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.32.0)
=> Update Shopify CLI to 2.32.0

shopify-cli@2.rb
I'm releasing a new version of the Shopify CLI, [2.32.1](https://github.com/Shopify/shopify-cli/releases/tag/v2.32.1)
=> Update Shopify CLI to 2.32.1

shopify-cli@2.rb
I'm releasing a new version of the Shopify CLI, [2.33.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.33.0)
=> Update Shopify CLI to 2.33.0

shopify-cli@2.rb
I'm releasing a new version of the Shopify CLI, [2.33.1](https://github.com/Shopify/shopify-cli/releases/tag/v2.33.1)
=> Update Shopify CLI to 2.33.1

shopify-cli@2.rb
I'm releasing a new version of the Shopify CLI, [2.34.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.34.0)
=> Update Shopify CLI to 2.34.0

shopify-vips.rb
Fix the missing `svgload` in shopify-vips. Inline comment:
```
```
=> shopify-vips: fix missing svgload

libgda@5.rb
Homebrew upgraded its libgda to 6 but some software still relies on version 5.
=> Add libgda@5

buildkite-agent.rb, merlin-certloader.rb, oauth-tunnel-client.rb, trino-certloader.rb
Brew started complaining during updates with the following:
```
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the shopify/shopify tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
/opt/homebrew/Library/Taps/shopify/homebrew-shopify/oauth-tunnel-client.rb:7
```
=> Replace deprecated plist methods with service blocks

trino-certloader.rb
bumping certloader verison to pickup the fix for git credentials https://github.com/Shopify/certloader/pull/287
=> bump certloader version

shopify-cli@2.rb
`deprecated` and `disabled` cannot work together. If you try to install `shopify-cli@2` right now you receive the deprecation message but you are able to install it.
=> Disable shopify-cli@2 installation

toxiproxy.rb
Toxiproxy 2.6.0 has been released.
The checksums were taken from the `checksums.txt` file in the assets section of the release: https://github.com/Shopify/toxiproxy/releases/tag/v2.6.0
=> Toxiproxy 2.6.0

shopify-vips.rb
Update shopify-vips to v8.15.0.
Test:
```
brew install file:///Users/dbl/src/github.com/Shopify/homebrew-shopify/shopify-vips.rb
```
=> Update shopify-vips to v8.15.0

shopify-vips.rb
Update to v8.15.1
**Changes since v8.15.0:** https://github.com/libvips/libvips/releases/tag/v8.15.1
=> shopify-vips: update to v8.15.1
